### PR TITLE
CMake workarounds for ubuntu capnproto 0.6.1 compatibility

### LINKED ISSUE #27: Ubuntu install fails
On Ubuntu 18.04 with cmake version 3.10.2, capnproto (0.6.1), libcapnp-dev (0.6.1):

```
cmake ..
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.65.1
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_PTHREAD_GETNAME_NP
-- Performing Test HAVE_PTHREAD_GETNAME_NP - Success
-- Performing Test HAVE_PTHREAD_THREADID_NP
-- Performing Test HAVE_PTHREAD_THREADID_NP - Failed
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP - Failed
-- Configuring done
CMake Error at CMakeLists.txt:73 (add_executable):
  Target "mpgen" links to target "CapnProto::capnp-rpc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:105 (add_executable):
  Target "mptest" links to target "CapnProto::capnp-rpc" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:105 (add_executable):
  Target "mptest" links to target "CapnProto::kj-test" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/dev/libmultiprocess/build
```

Looks like `cmake` can't find libcapnp-dev.

```
~/libmultiprocess/build$ make
[ 14%] Compiling Cap'n Proto schema include/mp/proxy.capnp
Scanning dependencies of target multiprocess
[ 14%] Compiling Cap'n Proto schema include/mp/proxy.capnp
[ 28%] Building CXX object CMakeFiles/multiprocess.dir/include/mp/proxy.capnp.c++.o
c++: error: /home/dev/libmultiprocess/include/mp/proxy.capnp.c++: No such file or directory
c++: fatal error: no input files
compilation terminated.
CMakeFiles/multiprocess.dir/build.make:69: recipe for target 'CMakeFiles/multiprocess.dir/include/mp/proxy.capnp.c++.o' failed
make[2]: *** [CMakeFiles/multiprocess.dir/include/mp/proxy.capnp.c++.o] Error 1
CMakeFiles/Makefile2:355: recipe for target 'CMakeFiles/multiprocess.dir/all' failed
make[1]: *** [CMakeFiles/multiprocess.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by ryanofsky**

### CODE REVIEW

**Comment by Sjors** [comment]
That did the trick for me, although (perhaps unrelated), `make test` says it can't find any.

**Comment by ryanofsky** [comment]
> That did the trick for me, although (perhaps unrelated), `make test` says it can't find any.

Thanks for testing! `make test` not doing anything is expected because ubuntu 0.6.1 package doesn't include the `libkj-test` library, so the `mptest` build is skipped

**Comment by Sjors** [comment]
This also fixed #26, except for `make test`, which throws

```
Test project /Users/sjors/dev/libmultiprocess/build
    Start 1: mptest
Could not find executable /Users/sjors/dev/libmultiprocess/build/mptest
Looked in the following places:
/Users/sjors/dev/libmultiprocess/build/mptest
....
Unable to find executable: /Users/sjors/dev/libmultiprocess/build/mptest
1/1 Test #1: mptest ...........................***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1
```

**Comment by ryanofsky** [comment]
> `make test` says it can't find any.

To clarify, if you're seeing error:

```
No tests were found!!!
```

with capnp 0.6.1 this is expected because the test can't be built.

But if you're seeing:

```
The following tests FAILED:
          1 - mptest (Not Run)
Errors while running CTest
```

that's a different problem. You need to run `make all test` instead of `make test` in that case (https://stackoverflow.com/questions/733475/cmake-ctest-make-test-doesnt-build-tests). I'll update the [readme](https://github.com/chaincodelabs/libmultiprocess/blob/master/README.md) to reflect this

**Pull request merged**
